### PR TITLE
Add from_raw, into_raw and as_ptr for ThinArc, as_ptr for Arc and add arc_swap support

### PR DESCRIPTION
**Pull request by NobodyXu**
Motivation for this PR:

[vorner/arc-swap](https://github.com/vorner/arc-swap) provides a way to atomically swapped an `Arc` (possibly `Option<Arc<T>>`) for another and its [`DefaultStrategy`](https://docs.rs/arc-swap/1.3.0/arc_swap/strategy/type.DefaultStrategy.html) guaranteed to be:

> - It is optimized for read-heavy situations, with possibly many concurrent read accesses from multiple threads. Readers don’t contend each other at all.
> - Readers are wait-free (with the exception of at most once in usize::MAX / 4 accesses, which is only lock-free).
> - Writers are lock-free.
> - Reclamation is exact ‒ the resource is released as soon as possible (works like RAII, not like a traditional garbage collector; can contain non-'static data).

It is a pretty useful crate and I'd love to use it along with `ThinArc` to store DSTs.

This PR adds new API for `ThinArc`:
 - `from_raw`
 - `into_raw`
 - `as_ptr`

And add `as_ptr` for `Arc`.

This PR also provides implementation of `arc_swap::RefCnt` for `Arc<T: Sized>` and `ThinArc` so that it can be used in `arc_swap` effortlessly by the users of this crate.

Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Comment by NobodyXu** [comment]
@Manishearth Hey, can you spend a little time to review this PR please?

**Comment by Manishearth** [comment]
I plan to review this, but I do not have that short a turnaround time, please be patient

**Comment by NobodyXu** [comment]
Thanks for the reply!

I don't mind waiting longer.

**Review by Manishearth — APPROVED** [review]

**Comment by Manishearth** [comment]
Thanks!

**Pull request merged**
